data1<-read.table("household_power_consumption.txt",sep=";",na.strings = "?",header = T)
data2<-subset(data1,data1$Date=="1/2/2007")
data3<-subset(data1,data1$Date=="2/2/2007")
datap<-rbind(data2,data3)
datatime<-paste(datap$Date,datap$Time)
dataq<-cbind(datap,datatime)
dataq$datatime<-strptime(dataq$datatime,"%d/%m/%Y%H:%M:%S")
Sys.setlocale("LC_TIME", "English")
png("plot2.png",width = 480,height = 480)
plot(dataq$datatime,datap$Global_active_power,type="l",xlab="",ylab = "Global Active Power",lty=1,col="black")
dev.off()