data1<-read.table("household_power_consumption.txt",sep=";",na.strings = "?",header = T)
data2<-subset(data1,data1$Date=="1/2/2007")
data3<-subset(data1,data1$Date=="2/2/2007")
datap<-rbind(data2,data3)
datatime<-paste(datap$Date,datap$Time)
dataq<-cbind(datap,datatime)
dataq$datatime<-strptime(dataq$datatime,"%d/%m/%Y%H:%M:%S")
Sys.setlocale("LC_TIME", "English")
png("plot4.png",width = 480,height = 480)
par(mfrow=c(2,2))
plot(dataq$datatime,datap$Global_active_power,type="l",xlab="",ylab = "Global Active Power",lty=1,col="black")
plot(dataq$datatime,datap$Voltage,type="l",xlab="datatime",ylab = "Voltage",lty=1,col="black")
plot(dataq$datatime,datap$Sub_metering_1,type="l",xlab="",ylab = "Energy sub metering",lty=1,col="black")
lines(dataq$datatime,datap$Sub_metering_2,col="red",lty=1)
lines(dataq$datatime,datap$Sub_metering_3,col="blue",lty=1)
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = c(1,1,1))
plot(dataq$datatime,datap$Global_reactive_power,type="l",xlab="datatime",ylab = "Global_reactive_power",lty=1,col="black")
dev.off()