data1<-read.table("household_power_consumption.txt",sep=";",na.strings = "?",header = T)
data2<-subset(data1,data1$Date=="1/2/2007")
data3<-subset(data1,data1$Date=="2/2/2007")
datap<-rbind(data2,data3)
png("plot1.png",width = 480,height = 480)
hist(datap$Global_active_power,col="red",xlab = "Global Active Power(kilowatts)",main = "Global Active Power",ylim = c(0,1200))
dev.off()